### ISSUE TITLE
Provide more summary data on available data in OPD

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#107]

**Comment by sowdm** [comment]
@potto216 Can you check out the summary branch in openpolicedata repo and in opd-examples and try out the new notebook for summaries. Are these summaries useful? Are there any other ways of summarizing data that might be useful?

**Comment by potto216** [comment]
@sowdm what will be the way to access the summary methods now that the dataset.py has been renamed to _dataset.py in the main branch?

**Comment by sowdm** [comment]
opd.datasets.{function_name}

**Comment by potto216** [comment]
When I use the latest version of main I get an error:
![image](https://user-images.githubusercontent.com/9930263/188336265-dffe72d8-f336-424c-b841-b605617fbd5b.png)

Do I need to first opd.datasets_query() to get the datasets?

**Comment by sowdm** [comment]
The summary branch hasn't been merged into the main branch yet. The summary branch renames _datasets to datasets, not the other way around. 

I was waiting any comments that you had about the Jupyter notebook on summaries prior to merging the summary branch with main
