### ISSUE TITLE
HTTP Error 500: Internal Server Error with Columbia, MO data

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#113]
Not including in source table. When testing, the 1st dataset can be loaded successfully but then an HTTP Error 500 is received even when waiting 1 minute between accessing each dataset. It is possible to download datasets successively in a brower but not with our CSV data loader.

Data is found here: https://www.como.gov/police/data-reporting-forms/

**Comment by potto216** [comment]
I was able to run the following without problem. Is this the data you had problems with?
```
url = "https://www.como.gov/wp-content/uploads/2022/03/CPD_vehicle_stop_data_2021.csv"
df1 = opd.data_loaders.load_csv(url, pbar=True)
df2 = opd.data_loaders.load_csv("https://www.como.gov/wp-content/uploads/2021/06/CPD_vehicle_stop_data_2020-6.csv", pbar=True)
df3 = opd.data_loaders.load_csv('https://www.como.gov/wp-content/uploads/2020/10/CPD_vehicle_stop_data_2019.csv')
df4 = opd.data_loaders.load_csv('https://www.como.gov/wp-content/uploads/2020/10/CPD_vehicle_stop_data_2018-2.csv', pbar=True)
df5 = opd.data_loaders.load_csv("https://www.como.gov/wp-content/uploads/2020/10/CPD_vehicle_stop_data_2017.csv")
df6 = opd.data_loaders.load_csv("https://www.como.gov/wp-content/uploads/2020/10/CPD_vehicle_stop_data_2016.csv", pbar=True)
```

**Comment by sowdm** [comment]
I had an issue with one of the tests for some other sources that I added. I removed that test as it is somewhat redundant. I added this data back in now not having any issues with this data. Going to close this.
