### ISSUE TITLE
sodapy is no longer maintained

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#119]
https://github.com/xmunoz/sodapy

How should this be handled?

**Comment by potto216** [comment]
I think we should continue using it and see if someone takes over the project or forks it by the end of the year. From looking at sodapy's issues it seems like there are multiple contributors so that is a plus for its future.

**Comment by sowdm** [comment]
Sounds good. I might fork it in case it ever goes offline.
