### ISSUE TITLE
Update About section on GitHub front page?

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#133]
Should we update the About section on our [front page](https://github.com/openpolicedata/openpolicedata) to include more keywords to help people find our package on PyPI and GitHub. Could add keywords related to the data types that we read (Arcgis, Socrata, Excel, CSV).
> A pandas-based Python package for police data analysis that provides easy access to incident-level police data for traffic stops, pedestrian stops, arrests, use of force, and other types of interactions.

@potto216 Perhaps something to discuss on Monday

**Comment by potto216** [comment]
Sounds good. Maybe also adding "government" to help with the search. Monday we should try different search terms to see how we rank and guide us in what to add.

**Comment by sowdm** [comment]
@potto216 What about this as a new intro on our readme?

> OpenPoliceData is a Python package that provides easy access to 276 (and growing) incident-level open datasets from police departments around the United States. Datasets include traffic stops, use of force, officer-involved shootings, complaints, and other types of police interactions. 
> 
> Users request data by department name and type of data, and the data is returned as a pandas DataFrame. There is no need to manually find the data online or to know how to work with open data APIs (ArcGIS, Socrata, etc.).

**Comment by potto216** [comment]
I like how that adds more context about the package such as number of datasets and the advantage of not needing to know how to work with ArcGIS etc.

**Comment by potto216** [comment]
I like how that adds more context about the package such as number of datasets and the advantage of not needing to know how to work with ArcGIS etc.
