### ISSUE TITLE
Add citations section in documentation for conferences

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#189]

**Comment by sowdm** [comment]
IRE 2023: https://schedules.ire.org/ire-2023/index.html#2250

**Comment by sowdm** [comment]
Planned home: Create citations menu item

**Comment by sowdm** [comment]
@potto216  I meant to have you check this out. Have a look at the citations page and let me know if you have any comments: https://openpolicedata.readthedocs.io/en/latest/citations/index.html

**Comment by potto216** [comment]
Looks good and the links worked for me.
