### ISSUE TITLE
Add documentation dropdown box to select version on readthedocs

### ISSUE THREAD

**Issue by potto216** [openpolicedata/openpolicedata#212]

**Comment by potto216** [comment]
Since our theme is `html_theme = 'pydata_sphinx_theme'` going to use https://pydata-sphinx-theme.readthedocs.io/en/v0.8.1/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions

**Comment by sowdm** [comment]
Completed in 93f79c993ecc4a0471e8456ec301d712f5b29c60
