### ISSUE TITLE
Add pytest parameter to only test changed rows based on Git diff line #'s

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#218]

**Comment by potto216** [comment]
So I will create a command line option --use-changed-rows for pytest. I'll add to the sections of the test code that use row selection such as skip, after that I will try to convert an argument to a fixture.  Refs:
https://stackoverflow.com/questions/71492103/pytest-argument-from-command-line-with-fixture
and test_preproc.py

**Comment by potto216** [comment]
@sowdm how should we handle the need to reference the opd-data repo? My test code is:
```
import subprocess
import csv
import io

def get_changed_rows(repo_dir,file_name):
    # Run git diff command to get differences between current state and previous commit
    cmd = f"git -C {repo_dir} diff HEAD~1 -- {file_name}"
    result = subprocess.check_output(cmd, shell=True).decode('utf-8')
    
    # Extract the lines that represent changes in the CSV (starting with "+" or "-")
    changed_lines = [line[1:] for line in result.split("\n") if line.startswith(("+", "-")) and not line.startswith(("---", "+++"))]
    
    # Convert lines to CSV rows
    changed_rows = list(csv.reader(io.StringIO("\n".join(changed_lines))))
    
    return changed_rows

file_name = "opd_source_table.csv"
repo_dir = "../opd-data"
changed_rows = get_changed_rows(repo_dir, file_name)
print(changed_rows)
```
Which produces 
```
[['California', 'San Jose', 'San Jose', 'San Jose Police Department', 'CALLS FOR SERVICE', '1/1/2011', '12/31/2011', '07/06/2023', 'Each record in this data set represents one incident. Please note; multiple calls received for any incident will be represented only once in this data set.', 'https://data.sanjoseca.gov/dataset/police-calls-for-service', '', 'https://data.sanjoseca.gov/dataset/c5929f1b-7dbe-445e-83ed-35cca0d3ca8b/resource/3aefa434-a81c-4c01-8be1-1495da203b5b/download/policecalls2011.csv', '2011', 'CSV', '', '', '', ''], ['California', 'San Jose', 'San Jose', 'San Jose Police Department', 'CALLS FOR SERVICE', '1/1/2012', '12/31/2012', '07/06/2023', 'Each record in this data set represents one incident. Please note; multiple calls received for any incident will be represented only once in this data set.', 'https://data.sanjoseca.gov/dataset/police-calls-for-service', '', 'https://data.sanjoseca.gov/dataset/c5929f1b-7dbe-445e-83ed-35cca0d3ca8b/resource/c27957d1-a224-43a5-a778-0303aa0c2b47/download/policecalls2012.csv', '2012', 'CSV', '', '', '', '']]
```

**Comment by sowdm** [comment]
Good question. I have the same directory structure as you so maybe default to "../opd-data"?

Probably the only option to change would be a pytest command line argument although it's just you and me at the moment so that's not super important. Could also just recommend in the CONTRIBUTING.MD that developers use our folder structure

**Comment by sowdm** [comment]
I just realized those San Jose datasets are probably ones that I deleted so the change that is listed above is from the remote. This brings up a couple things to consider:
- Your code should only identify local changes to test. I would probably additionally say only uncommitted changes.
- Changes that are deletions should be ignored

**Comment by potto216** [comment]
This will only use uncommitted changes in working copy

**Comment by potto216** [comment]
@sowdm what are your thoughts on integrating with existing tests. The existing testing in test_datasets.py use the csv filename. One possibility is to modify the `get_datasets` function to return either all the rows or just the changed rows depending on the --use-changed-rows flag. The branch changes are https://github.com/openpolicedata/openpolicedata/compare/main...218-test-changed-rows

**Comment by sowdm** [comment]
Modifying get_datasets makes sense. It's redefined in a few of the test files. Feel free to modify to make it defined only once.
