### ISSUE TITLE
Stop supporting Python 3.7?

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#230]
It has reached end of life: https://devguide.python.org/versions/

https://github.com/openpolicedata/openpolicedata/blob/main/pyproject.toml#L14

**Comment by sowdm** [comment]
@potto216 Thoughts?

**Comment by potto216** [comment]
I would suggest updating the toml to a minimum of 3.8. I am using 3.8 for testing, but not doing anything with 3.7. How about you?

**Comment by sowdm** [comment]
I do test with the min and latest Python versions in the toml.

Maybe the answer is that even if our code works with unsupported Python
versions, we probably don't want them running on our computers due to
potential security flaws

**Comment by sowdm** [comment]
We are going to stop supporting 3.7 due to security concerns.

Can now utilize these features in code: https://docs.python.org/3/whatsnew/3.8.html
