### ISSUE TITLE
Denver STOPS data missing

### ISSUE THREAD

**Issue by guhaishuo** [openpolicedata/openpolicedata#286]
It seems that the link is wrong.
`OPD_DataUnavailableError: ('https://services1.arcgis.com/zdB7qR0BtYrg0Xpl/arcgis/rest/services/ODC_CRIME_STOPS_P/FeatureServer/32/', 'Error returned by ArcGIS query', 'code', 499, 'message', 'Token Required', 'messageCode', 'GWM_0003', 'details', 'Token Required')`

**Comment by sowdm** [comment]
Yes, the link is dead. Denver recently updated their open data website and when they did, the Stops and Officer-Involved Shootings datasets were [no longer available](https://opendata-geospatialdenver.hub.arcgis.com/search?categories=%252Fcategories%252Fpublic%2520safety). We contacted them about whether this data would be made available again but have not heard back. It may help if they hear from you as well. [Here](https://survey123.arcgis.com/share/fa27ca29ff0346aabadf8ae60a64442a) is the contact.

If you need the data, I have a backup that I can share. You can contact me by [email](openpolicedata@gmail.com) for this data. 

Unfortunately, we don't have a way to host large datasets current to allow this data to continue to be part of OpenPoliceData. If you have suggestions, we would love to hear them.

Finally, this dataset was included in our list of [site outages](https://github.com/openpolicedata/opd-data/blob/main/outages.csv). We had an [issue](https://github.com/openpolicedata/openpolicedata/issues/134) for notifying the user if a site was known to not be working. I have now added that issue for completion for the next release. I have also [removed the Denver Stops data from availability in OPD](https://github.com/openpolicedata/opd-data/commit/1f18d051de18a892211139a5707ebdbcb5811ce6) until the data is restored.

**Comment by guhaishuo** [comment]
Thank you for your prompt response. Regarding data storage, I suggest using a public cloud service like Google Cloud. OpenPoliceData is very helpful for my research. Thanks!
