### ISSUE TITLE
Should  our package be added to conda-forge?

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#54]
Our repo is currently dependent on geopandas. In Windows, it is easier to install geopandas using conda. If we add our package and required packages (as needed) to conda-forge, our installation instructions could be simplified to: conda install -c conda-forge openpolicedata

https://conda-forge.org/docs/user/introduction.html
https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-staging-process

Some of our packages (at least Socrata) aren't available through conda, but it looks like we could add them to conda-forge: "You don’t have to be the upstream maintainer of a package in order to contribute it to conda-forge. "

Example installation using conda-forge package: https://github.com/cenpy-devs/cenpy

**Comment by potto216** [comment]
We talked about this and decided we should add our package to conda-forge. We will first see if we can just have OPD on pypi and link to conda-forge or we need to have our package on conda. First investigate what needs to be done to get package on conda, then decide steps on what to do for package placement (PyPi, conda etc)

**Comment by potto216** [comment]
I'm investigating if we need all our dependences on conda-forge based on:
"Avoid external dependencies[¶](https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies)
As a general rule: all dependencies have to be packaged by conda-forge as well. This is necessary to assure [ABI](https://conda-forge.org/docs/misc/00_intro.html#term-ABI) compatibility for all our packages."
https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-staging-process.

**Comment by potto216** [comment]
Going to take a step back and first get the package installed on PyPi. This will allow us to resolve the issue if GeoPanadas can be installed under Windows or needs to be an optional package. Once we have a working PyPi installation we can use grayskull to generate the meta.yaml file for conda-forge.

**Comment by sowdm** [comment]
Updates have now been pushed that make GeoPandas optional. Should be ready to attempt to add package to pip

**Comment by potto216** [comment]
Able to create the `meta.yaml` file for conda using our latest code packaged on pypi test using the command:
`grayskull pypi --pypi-url https://test.pypi.org/pypi openpolicedata-sowdm`
Did you want to create a package without the -sowdm?
Also we need a version number

**Comment by sowdm** [comment]
Does it need a -{something} at the end or can it just be openpolicedata?

Thoughts on the version #? You probably have more experience with that than me.

**Comment by potto216** [comment]
It should be able to just be called openpolicedata. If you create the account on test pypi I can add the package. I would recommend starting with version 0.1.0 where for major.minor.patch we follow
major => change when adding features that breaks backwards compatibility of something
minor => change when adding features
patch => bug fixes

**Comment by sowdm** [comment]
0.1.0 sounds good

**Comment by sowdm** [comment]
I now seem to recall that on TestPyPI, they recommend the -username after your package name so maybe we should use openpolicedata-sowdm for now. I'm trying to find the documentation but haven't been able to yet.

**Comment by potto216** [comment]
1. Need to create openpolicedata on pypi
2. Test install from pypi-test
3. Upload version 0.1.0 to pypi
4. Create Grayskull script for conda-forge
5. Submit to conda-forge

**Comment by sowdm** [comment]
@potto216 Additional question for testing wheel install: You've trying installing from pypi-test. Can you install directly from a wheel file saved locally? [Here](https://stackoverflow.com/questions/27885397/how-do-i-install-a-python-package-with-a-whl-file#:~:text=%20To%20be%20able%20to%20install%20wheel%20files,%27Run%20as%20administrator%27%20checkbox%20in%20the...%20More%20) are directions for installing opd from wheel. This might avoid having to change versions every time on pypi-test and save a few steps when testing if new installer versions work

**Comment by sowdm** [comment]
Removed geopandas from setup.cfg, generated a wheel file, and successfully pip installled from the local wheel file in dist folder

**Comment by potto216** [comment]
Still unable to to install on ubuntu using 0.1.3 getting errors like
```
ERROR: Could not find a version that satisfies the requirement pandas (from openpolicedata-sowdm) (from versions: none)
ERROR: No matching distribution found for pandas (from openpolicedata-sowdm)
```
and
```
Collecting sodapy
  Downloading https://test-files.pythonhosted.org/packages/49/30/15d83581870d4e6f71a0a77e1c7bdc368ab6113775fa5977e9cca6101e77/sodapy-0.1.7.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/user/tmp/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xkibm1sg/sodapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xkibm1sg/sodapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xkibm1sg/sodapy/pip-egg-info
         cwd: /tmp/pip-install-xkibm1sg/sodapy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xkibm1sg/sodapy/setup.py", line 4, in <module>
        from past.builtins import execfile
    ModuleNotFoundError: No module named 'past'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

At a minimum found the following packages need to be installed before a pip download
```
sudo apt-get install libkrb5-dev build-essential libssl-dev libffi-dev python3-dev

pip install wheel
pip install gssapi
```

Still working through the bugs.

**Comment by sowdm** [comment]
I just tried installing from Windows and got an error finding the dependencies too.

The first line of the install says:
`Looking in indexes: https://test.pypi.org/simple/`

Maybe it's only looking for the dependencies in test.pypi?

Then, I got the same error as you
```
Collecting sodapy
  Downloading https://test-files.pythonhosted.org/packages/49/30/15d83581870d4e6f71a0a77e1c7bdc368ab6113775fa5977e9cca6101e77/sodapy-0.1.7.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\matth\.conda\envs\opd-test\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matth\\AppData\\Local\\Temp\\pip-install-r29w7x1q\\sodapy_cd28b27f15154e559b9a5ecf09aa2b2d\\setup.py'"'"'; __file__='"'"'C:\\Users\\matth\\AppData\\Local\\Temp\\pip-install-r29w7x1q\\sodapy_cd28b27f15154e559b9a5ecf09aa2b2d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\matth\AppData\Local\Temp\pip-pip-egg-info-_tvfyqmh'
         cwd: C:\Users\matth\AppData\Local\Temp\pip-install-r29w7x1q\sodapy_cd28b27f15154e559b9a5ecf09aa2b2d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\matth\AppData\Local\Temp\pip-install-r29w7x1q\sodapy_cd28b27f15154e559b9a5ecf09aa2b2d\setup.py", line 4, in <module>
        from past.builtins import execfile
    ModuleNotFoundError: No module named 'past'
```

Note that it downloaded the file from https://test-files.pythonhosted.org/packages/49/30/15d83581870d4e6f71a0a77e1c7bdc368ab6113775fa5977e9cca6101e77/sodapy-0.1.7.tar.gz (13 kB)

I'm going to test 2 things:
1. Downloading the wheel from testpypi and then installing it from file
2. Checking if there is any way to tell pip where to look for dependencies

**Comment by sowdm** [comment]
@potto216 
I found the answer here: https://stackoverflow.com/questions/34514703/pip-install-from-pypi-works-but-from-testpypi-fails-cannot-find-requirements

It pointed me to: https://packaging.python.org/en/latest/guides/using-testpypi/

which suggested running 
`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ your-package`

which works!

**Comment by sowdm** [comment]
I just created a new Ubuntu VM, followed your instructions

`sudo apt-get install libkrb5-dev build-essential libssl-dev libffi-dev python3-dev` 

and then ran 

`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ openpolicedata-sowdm`

This successfully installed, and I was able to import and load some data.

I think the next step is for me to upload to regular PyPI?

**Comment by sowdm** [comment]
@potto216 We are live on PyPI! 
https://pypi.org/project/openpolicedata/

**Comment by sowdm** [comment]
What's your username on PyPI so I can invite you to be an owner?

**Comment by potto216** [comment]
Awesome! I got it to install with ` pip install openpolicedata` . I'll work on the conda-forge script and send you my PyPI info

**Comment by potto216** [comment]
Submitted a PR to have our package added on conda-forge https://github.com/conda-forge/staged-recipes/pull/19327

**Comment by potto216** [comment]
Find out if need re-approval from conda-forge when updates are made to our package

**Comment by potto216** [comment]
Did not get a response from the PR or using the suggested bot command @conda-forge-admin. Trying their [glitter channel](https://gitter.im/conda-forge/conda-forge.github.io)

**Comment by potto216** [comment]
Was able to get a response from the conda team on glitter and I would also need to submit requests and be the maintainer for arcgis, sodapy. I created recipes for these, but they failed the automatic checks. I felt the amount of effort to get these to pass exceeded the benefit so I'm going to close the branch. I also deleted the [PR on conda](https://github.com/conda-forge/staged-recipes/pull/19327)
