### ISSUE TITLE
modify get_years and get_agencies  to allow user to force loading of URLs pointing to CSVs or Excel files

### ISSUE THREAD

**Issue by potto216** [openpolicedata/openpolicedata#96]
Modify get_years to allow user to force loading of URLs pointing to CSVs or Excel files for cases where they are only interested in the years within the data set. 
https://github.com/openpolicedata/openpolicedata/blob/8fa246bb4e858e9b1fd9a19d4aa3f73c343c1c41/openpolicedata/data.py#L225
Because this is a slow operation if the force_true flag is not set or false then throw an error explaining if all they are interested in the data set are the years then use force_true, otherwise reference load_from_url and how tp print its documentation where an example would be on extracting the years from the loaded data. 

Do the same for get_agencies
https://github.com/openpolicedata/openpolicedata/blob/8fa246bb4e858e9b1fd9a19d4aa3f73c343c1c41/openpolicedata/data.py#L285

**Comment by sowdm** [comment]
Completed in 8e83a243a53b157a2f301c5f833b264b45e481ce
